### PR TITLE
[UPG] pre-commit

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
Thanks !

/ocabot merge nobump

**Comment by mileo** [comment]
@rvalyi @legalsylvain i think that the bot crash...

**Review by marcelsavegnago — APPROVED** [review]

**Comment by PierrickBrun** [comment]
Well, github actions only run on PR and master branch so the bot will never have its tests finished.

**Pull request merged**
